/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "on-primary-fixed": "#000000",
              "on-secondary-container": "#203ea2",
              "tertiary-fixed-dim": "#e48fec",
              "inverse-surface": "#0b0f10",
              "on-primary-fixed-variant": "#002a61",
              "on-error": "#ffefee",
              "outline": "#747779",
              "on-tertiary-fixed-variant": "#6a1f76",
              "on-primary": "#f0f2ff",
              "tertiary-dim": "#7a2f86",
              "on-tertiary-container": "#60136d",
              "surface-container-high": "#dfe3e6",
              "tertiary-fixed": "#f39cfb",
              "surface-variant": "#d9dde0",
              "error-container": "#fb5151",
              "error-dim": "#9f0519",
              "error": "#b31b25",
              "on-secondary-fixed-variant": "#2c48ac",
              "on-surface": "#2c2f31",
              "surface": "#f5f7f9",
              "surface-container-highest": "#d9dde0",
              "secondary-dim": "#2b47ab",
              "outline-variant": "#abadaf",
              "primary-fixed": "#6c9fff",
              "secondary-fixed": "#c6cfff",
              "surface-tint": "#0058bb",
              "primary-container": "#6c9fff",
              "surface-dim": "#d0d5d8",
              "tertiary-container": "#f39cfb",
              "surface-bright": "#f5f7f9",
              "primary-dim": "#004ca4",
              "on-primary-container": "#00214f",
              "surface-container-lowest": "#ffffff",
              "on-surface-variant": "#595c5e",
              "surface-container": "#e5e9eb",
              "on-secondary-fixed": "#00288d",
              "primary-fixed-dim": "#5191ff",
              "on-error-container": "#570008",
              "surface-container-low": "#eef1f3",
              "inverse-on-surface": "#9a9d9f",
              "tertiary": "#883c93",
              "secondary-fixed-dim": "#b4c1ff",
              "primary": "#0058bb",
              "on-background": "#2c2f31",
              "inverse-primary": "#4b8eff",
              "secondary-container": "#c6cfff",
              "on-tertiary": "#ffeefb",
              "on-secondary": "#f2f1ff",
              "secondary": "#3853b7",
              "background": "#f5f7f9",
              "on-tertiary-fixed": "#41004d"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "fontFamily": {
              "headline": ["Space Grotesk"],
              "body": ["Inter"],
              "label": ["Inter"]
      }
    },
  },
  plugins: [],
}
