spring.application.name=backend
server.port=${PORT:8080}
server.address=0.0.0.0
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/blogforum_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:005928}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=vz9QzE8S4tH3v2E7N1qB6K2jU7R4eA1xM9F8vP7mNcQ=
jwt.expiration=86400000

# File Upload Configuration
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Google Auth
google.client.id=131278915848-0l7blp4v8bv7m9fkvs4n89r74767k7ll.apps.googleusercontent.com

# Telegram Bot Configuration
telegram.bot.token=8639970533:AAGYDi-tzQkG3gP5OLpMggj753_E-mScQtE
telegram.bot.admin-chat-id=1845357537
telegram.bot.frontend-url=http://localhost:4200
telegram.bot.username=BlogForumNotifyBot

# Cloudinary Configuration 
cloudinary.cloud-name=dftzgslbm
cloudinary.api-key=188266912746694
cloudinary.api-secret=h7gbqa-PhrZq4SN4meE77KPWSn4
cloudinary.folder=blogforum
